# Use a Node.js image for development
FROM node:16

# Set the working directory
WORKDIR /frontend

# Install dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy the source code
COPY frontend/ .

# Expose the React dev server port
EXPOSE 3000

# Command to start React app
CMD ["npm", "start"]
