version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: trader_backend
    ports:
      - "5000:5000"
    # If your backend depends on other services (databases, etc.),
    # you can add depends_on here.

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: trader_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
