version: '3.9'

services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      # You can pass environment variables here if needed.
      - FLASK_ENV=development
    volumes:
      - ./backend:/app  # Useful for development; remove or adjust for production.

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/docker/Dockerfile
    ports:
      - "3000:80"  # Maps port 80 inside the container to port 3000 on your host.
    volumes:
      - ./frontend:/app  # Optional: useful for hot-reloading during development.
